### ISSUE TITLE
Some points to be noted

### ISSUE THREAD

**Issue by mimisabel** [plexicus/web#11]
Hi Vivek, could you change the first parragraph for the second one?

Some Important Points to be noted
The first is a non technical method which requires the use of adware removal software. Download free adware and spyware removal software and use advanced tools getting infected.
- Search Management System
Staying calm, composed and maintaining strong self esteem in today’s tough environment can be difficult but is not impossible if you follow a few simple guidelines.
- Data Synchronization Options
We all live in an age that belongs to the young at heart. Life that is becoming extremely fast, day to day, also asks us to remain physically young. Young at heart.
- Team Management Facilities
Increasing prosperity in our lives can be accomplished by having the right frame of mind. The truth is, our thoughts are very powerful. They are capable of influencing.
- Schedule Adjustment System
Have you ever had a problem with a burned light? Thanks to the effort of Thomas Edison we no longer need to invent a light bulb. We just go to the store.

>>>>>>>>>>

Key Features
Plexicus automatically assess and understand risk across your entire infrastructure
- Deep attack surface discovery
Dynamically discover and automatically assess new infrastructure on a weekly basis, identifying external-facing assets to ensure complete discovery
- Inventory and Real Priorization
Comprehensive asset inventory with risk priorization for you to gain a better understanding of the risk in your modern environment
- Remediation
Real insights with high impact. Precise priorities, the right remedies, and meaningful analytics. 
- Built in Dashboard
Easy to use dashboard to quantify how your risk has changed over time, and identify your most critical areas for improvement

**Comment by webuimaker** [comment]
DONE
