### ISSUE TITLE
Free Trial

### ISSUE THREAD

**Issue by mimisabel** [plexicus/web#12]
Hi Vivek, Could you replace the "Free Trial" button for "Book your demo"? Could you redirect it to the "Contact us" form, once the button is clicked?

**Comment by webuimaker** [comment]
DONE

**Comment by mimisabel** [comment]
Hi Vivek, could you redirect all of the buttons that say "Book you demo" to the "Contact us" form?
![image](https://user-images.githubusercontent.com/68071180/104727394-42abb600-5703-11eb-8899-4307a6aeb950.png)
Home and about us page
![image](https://user-images.githubusercontent.com/68071180/104727433-50613b80-5703-11eb-9293-f3b406abcfdc.png)
Home / About us page / Pricing
![image](https://user-images.githubusercontent.com/68071180/104727456-5bb46700-5703-11eb-860b-3443c2bea19a.png)
