### ISSUE TITLE
Blog post - Uncategorized 

### ISSUE THREAD

**Issue by mimisabel** [plexicus/web#14]
Hi Vivek, is it possible to change this 👇🏻?

Could you please change it and tell us how?

![image](https://user-images.githubusercontent.com/68071180/104729275-307f4700-5706-11eb-837a-f42179df0a68.png)

**Comment by webuimaker** [comment]
You can add 
category: [Vision] 

in posts

**Comment by mimisabel** [comment]
Hi Vivek, sorry to bother you again but when I clic on the edit icon, it appears this message. 

![image](https://user-images.githubusercontent.com/68071180/104929679-324d4280-5972-11eb-9ff1-f726ef845835.png)
