### ISSUE TITLE
Blog post - Banner

### ISSUE THREAD

**Issue by mimisabel** [plexicus/web#15]
Hi Vivek, 

I wanted to change the banner on a post (https://www.plexicus.com/2019/09/04/how-to-set-intentions-that-energize-you.html)
![image](https://user-images.githubusercontent.com/68071180/104730571-4a218e00-5708-11eb-8cf8-61f265a932f2.png)

So I replace the image inside the post with a new one that I added (img/blog/b2.png) 
![image](https://user-images.githubusercontent.com/68071180/104730802-af757f00-5708-11eb-96f7-15729ccda3f0.png)

However I see that it changed the cover and not the banner, Could you let me know how can I change the banner of a post? 
![image](https://user-images.githubusercontent.com/68071180/104730859-d633b580-5708-11eb-896f-50548233eb65.png)

**Comment by webuimaker** [comment]
image: 'img/blog/hero-blog.jpg'

yes correct in post files 

see here : http://127.0.0.1:4000/vision/2019/09/06/motivation-and-your-personal-vision-an-force3.html

**Comment by mimisabel** [comment]
Thanks Vivek, I just checked and it worked!
