### ISSUE TITLE
Contact us - Hubspot Form

### ISSUE THREAD

**Issue by mimisabel** [plexicus/web#17]
Hi Vivek, 

Could you please hide/delete the google map with the information within it?

We would like to embed a Hubspot form 

To embed this form, simply copy and paste the code below into the HTML code on your website. 
__________________________

<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/shell.js"></script>
<script>
  hbspt.forms.create({
	portalId: "9213588",
	formId: "931ceb44-d0cb-45fa-816c-54c65eb54da2"
});
</script>

__________________________

It should look like this:
![image](https://user-images.githubusercontent.com/68071180/104780895-82988a80-574f-11eb-8d47-ab9d6adbe335.png)

**Comment by webuimaker** [comment]
DONE
