### ISSUE TITLE
Early bird Acess - Hubspot Form

### ISSUE THREAD

**Issue by mimisabel** [plexicus/web#18]
Hi Vivek,

Could you please hide/delete the form on the home page?

We would like to embed a Hubspot form

To embed this form, simply copy and paste the code below into the HTML code on your website.
_________________

<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/shell.js"></script>
<script>
  hbspt.forms.create({
	portalId: "9213588",
	formId: "8e16b02d-bfa5-45bc-9c52-2beb78e6201a"
});
</script>
__________________

It should look like this:

![image](https://user-images.githubusercontent.com/68071180/104782916-030cba80-5753-11eb-9eed-203b35e027b2.png)

**Comment by webuimaker** [comment]
Done
