### ISSUE TITLE
Early bird Acess - Button

### ISSUE THREAD

**Issue by mimisabel** [plexicus/web#19]
Hi Vivek, 

Could you reemplace "Book you demo" button with "Early bird access"? 
And redirect it to the "Plexicus early acess" section on the home page? 

![image](https://user-images.githubusercontent.com/68071180/104783230-8f1ee200-5753-11eb-8476-203d37aa7dad.png)

These are the buttons to change the name and redirect it to...

- Home
![image](https://user-images.githubusercontent.com/68071180/104783314-c097ad80-5753-11eb-9ff1-74a25cb6014c.png)

- Home
![image](https://user-images.githubusercontent.com/68071180/104727394-42abb600-5703-11eb-8899-4307a6aeb950.png)

- Home and about us page
![image](https://user-images.githubusercontent.com/68071180/104727433-50613b80-5703-11eb-9293-f3b406abcfdc.png)

- Home / About us page / Pricing
![image](https://user-images.githubusercontent.com/68071180/104727456-5bb46700-5703-11eb-860b-3443c2bea19a.png)

**Comment by webuimaker** [comment]
DONE
