### ISSUE TITLE
Blog Carusel & Title

### ISSUE THREAD

**Issue by mimisabel** [plexicus/web#21]
Hi Vivek, 

I thought that by adding images to the posts, the carusel at the beginning would change, the same as the title
However I see they are still the same, could you please let me know how to change it?

![image](https://user-images.githubusercontent.com/68071180/104933650-2d3ec200-5977-11eb-9619-d441445007c7.png)

**Comment by webuimaker** [comment]
No, You are wrong, if you suppose you have created more than 200 posts then 200 carousel  with image and title. It will be too heavy and take too much time in loading. 

So you can change it from hero.yml under _data  like below

blog_slider:
  - image: 'img/hero/hero-blog.jpg'
    author: 'Sir Alex James'
    title: 'The Idea Of God Is <br /> Not Henceforth Relevant'
    category: 'Technical'

  - image: 'img/hero/hero-blog.jpg'
    author: 'Sir Alex James'
    title: 'The Idea Of God Is <br /> Not Henceforth Relevant '
    category: 'Art &amp; Fantacy'
