### ISSUE TITLE
External Links

### ISSUE THREAD

**Issue by mimisabel** [plexicus/web#22]
Hi Vivek, could you please make them external links, so when you clic on them, you do not leave the home page of Plexicus, instead a new tab can be open? And could you please make them the same size or height?

![image](https://user-images.githubusercontent.com/68071180/104934964-a68ae480-5978-11eb-80c2-9a715f12d249.png)

Could you also add the Linkedin and Twitter accounts as external links to the social buttons?

https://www.linkedin.com/company/plexicus
https://twitter.com/Plexicus1/

**Comment by webuimaker** [comment]
Done

**Comment by mimisabel** [comment]
Hi Vivek, the external links of Linkedin and Twitter are not working, could you please check?

**Comment by webuimaker** [comment]
Please provide your  Linkedin and Twitter links right now blank it, please provide I will update it.

**Comment by mimisabel** [comment]
Sure, please add them as external links, thanks!

https://www.linkedin.com/company/plexicus
https://twitter.com/Plexicus1/

**Comment by webuimaker** [comment]
DONE
