### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by mimisabel** [plexicus/web#23]
Hi Vivek, 
I changed the text of Review, however if we have more reviews in the future, could you let us know what we would have to do in order for the other review to be visible? Thanks!

**Comment by webuimaker** [comment]
Great, you need to add more reviews like before, copy paste, and change according to new. 

# Client
- author: 'Julio Martin'
  avatar: '/img/review/user-img.png'
  position: 'Head of Security, Spanish MSSP.'
  quotes: 'Plexicus is a great tool for maintaining the security of the organization by identifying vulnerabilities in terms of security. This tool shows me the top actions we can do to reduce risk.'
