### ISSUE TITLE
Illustrations

### ISSUE THREAD

**Issue by mimisabel** [plexicus/web#24]
Hi Vivek, We understand design might not be in your skillset however please let us know if you could, your response is very important for us

![image](https://user-images.githubusercontent.com/68071180/104937399-b7892500-597b-11eb-8506-349a1216e642.png)

**Comment by webuimaker** [comment]
Hi Isabel, 

Yes, but I only help to search images from Google and provide them to you.  Thanks you can understand and I hope you are happy to work.
