### ISSUE TITLE
Pricing for Assessments

### ISSUE THREAD

**Issue by mimisabel** [plexicus/web#6]
Hi Vivek, would it be possible to add another pricing for assessments? 
![image](https://user-images.githubusercontent.com/68071180/104594819-b3899a00-563f-11eb-9186-3851689ae560.png)

**Comment by webuimaker** [comment]
DONE

**Comment by mimisabel** [comment]
Hi Vivek, 

Sorry if I am very picky with this, it's just that the first three /basic, advanced, agency/ are within the attack surface scan, and assessments are only for web/mobile apps

So maybe you could separate the first three more from the last one, maybe add them into separate rectangles and add a title for attack surface scan and another one just for assessments, If it's too complicated, maybe you can just place assessment below. Those are *ideas* that we came up with, but we highly recommend that you check a way to make that differentiation that it can be easy for you, nicely done and visually appealing.

It's just that we would not want people to get confused 👍

**Comment by webuimaker** [comment]
DONE
