### ISSUE TITLE
Contact Location and Map message

### ISSUE THREAD

**Issue by mimisabel** [plexicus/web#8]
Hi Vivek, when I clic on Contact, It takes me to another page with a google map behind, 
Do you know the reason it says "For development purposes only"? Is it possible to hide/delete that message?
Could you please reemplace "Santa monica bullevard" for "Downtown Madrid"?

**Comment by webuimaker** [comment]
its generated by Google and google provide a code for use Google map code. you need to generate Google map code and send me back if you want to use map.
